# -*- coding: utf-8 -*-
"""Student_Grade_Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19KK8sHuCg53tCPGuOY_6DHhrLZwl6n0_
"""

from google.colab import files

uploaded = files.upload()

def calculate_grade(avg):
    if avg >= 90:
        return "A"
    elif avg >= 80:
        return "B"
    elif avg >= 70:
        return "C"
    elif avg >= 60:
        return "D"
    else:
        return "F"

try:
    with open("student.txt", "r") as file:
        for line in file:
            data = line.strip().split(",")

            name = data[0]
            marks = list(map(int, data[1:]))

            average = sum(marks) / len(marks)

            grade = calculate_grade(average)

            print("-" * 30)
            print("Name   :", name)
            print("Marks  :", marks)
            print("Average:", round(average, 2))
            print("Grade  :", grade)

except FileNotFoundError:
    print("student.txt file not found.")